### ISSUE TITLE
index out of range when doing select from Win32_OperatingSystem

### ISSUE THREAD

**Issue by yoshi314** [simply42/check_wmi_plus_wmic_dropin#2]
until now, i've been running wmic with 

``` 
wmic.py '--namespace=root\CIMV2' -U user%pass //10.117.201.63 'SELECT BuildNumber FROM Win32_OperatingSystem'
ERROR:root:list index out of range
```

even querying a specific one column produces the same error

**Comment by wornet-aer** [comment]
Hi @yoshi314,
obviously we didn't think about upper case queries when implementing. 
This should be fixed now, please give it another try. :-)

Cheers,
Andreas

**Comment by yoshi314** [comment]
yeah, i just noticed that From or FROM causes a problem.
