### ISSUE TITLE
is there a way to turn this into a daemon?

### ISSUE THREAD

**Issue by yoshi314** [simply42/check_wmi_plus_wmic_dropin#3]
Not familiar with python too much, and i have an issue - i run this script as replacement for wmic on my icinga2 server. 

I have hundreds of wmi checks, and each invocation of wmic.py causes quite a bit of load. Possibly, running this as a daemon that's constantly loaded and only processes requests might help reduce the burden on the monitoring setup.

Just wondering whether this is feasible.

**Comment by wornet-aer** [comment]
Hi Yoshi,

how many Windows/WMI hosts do you have? We only have some few Windows machines here, so there wasn't any noticeable difference between the old wmic and the Python version.

After we implemented this wmic drop-in, we found out that there already had been an earlier attempt by @dlundgren. There is also kind of the same issue than yours, but unfortunately no response or implementation yet: https://github.com/dlundgren/py-wmi-client/issues/3

I've just done a quick speed comparison between the old wmic and our Python version. The Python one seems to be six times slower, than the old implementation written in C.

However, I'm not sure if we could speed things up with using a daemon or if it's just the Python WMI which needs more time per request. Maybe someone who is more familiar with Python can shed some light on this?

Cheers,
Andreas

**Comment by yoshi314** [comment]
from a cursory glance, ~ 5200 checks.

Python is causing extreme load on the machine, somewhere around 50-150.

**Comment by wornet-aer** [comment]
Okay, that's definitely an amount of hosts, where a deamon or super fast wmic implementation is needed.
Could you please try if the other Python wmic drop-in has the same performance issues?
https://github.com/dlundgren/py-wmi-client

**Comment by yoshi314** [comment]
I will give it a shot, but in the meantime i finally managed to get icinga2 ha setup going and load dropped considerably.

I'll do some comparisons  between each in the meantime

**Comment by hege-li** [comment]
It's the python impacket module itself which is painfully slow, forking penalty is miniscule compared to that. Simple to check with running old wmic and python from command line, 0.14 vs 3.2 sec to list Win32_Process etc, you can see how it's super slow to print the individual result lines. Not even using pypy3 helps (could help for a long running daemon version though).

Sadly doesn't seem to be important for the devs:
https://github.com/SecureAuthCorp/impacket/issues/130

**Comment by hege-li** [comment]
FYI, found another library that is almost as fast as native wmic:

https://github.com/cesbit/aiowmi

I was able to hack up a working client with the example given there. Speed compared to native, about 0.14 vs 0.21s.

**Comment by wornet-aer** [comment]
Thanks for sharing your findings! 
The [aiowmi](https://github.com/cesbit/aiowmi) variant definitely looks promising. We will give it a shot and may switch to this wmi implementation later.

**Comment by majurgens** [comment]
aiowmi already includes a daemon https://github.com/cesbit/aiowmi/tree/main/contrib/wmic_server that is used by check wmi plus

**Comment by wornet-aer** [comment]
That sounds great! I'll be including a reference to this repo into our README, so that everyone who is searching for this will definitely find the best solution. This issue will be also closed then. If you're looking for a modern wmic implementation, please use `aiowmi`.

**Comment by yoshi314** [comment]
i temporarily worked this around by compiling this plugin into C code. The reduction is significant.
