### ISSUE TITLE
Option -A to read from a file is not working

### ISSUE THREAD

**Issue by gmourani** [simply42/check_wmi_plus_wmic_dropin#4]
Hello,

I can't use the -A option to read the credentials from the file instead of executing them from the CLI. Can you add this option like wmic did?

Regards,

**Comment by wornet-aer** [comment]
Unfortunately our drop-in currently does not support the -A option. Maybe we will add it later.
Until then you can try the earlier version of an wmic drop-in from @dlundgren: https://github.com/dlundgren/py-wmi-client

**Comment by wornet-aer** [comment]
The auth-file feature has now been implemented by #6.
