### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by selcats** [simply42/check_wmi_plus_wmic_dropin#5]
Hi,

We followed the instructions for the drop in and cant get anything to work.  WMIC returns usage info but we cant get that format working.  The check_wmi_plus.pl gives the same errors about format etc.. I know we can't use -A.   We have python 3 on our server.   thanks

**Comment by selcats** [comment]
this is the error in nagios
UNKNOWN - The WMI query had problems. The error text from wmic is: usage: wmic [-h] -U USERNAME [-v] [-n NAMESPACE] host query

**Comment by selcats** [comment]
We are using our original commands we just replaced the -A with -u and -p but it doesnt seem to want to take anything from the check_wmi_plus.pl formats

**Comment by wornet-aer** [comment]
Hi selcats,

could you please provide us the full command or command template you are using?
Python3 should be working fine. Have you tried running a sample WMIC command manually from shell?

For example:
`wmic.py -U 'username%password' --namespace 'root/cimv2' '//10.0.0.1' 'SELECT Version FROM Win32_OperatingSystem'`

You can also compare the results to your old wmic if you still have it installed.

Cheers
Andreas

**Comment by slyguy2000** [comment]
this is what I get... (username/password, IP masked)  these work on this server with check_wmi_plus.pl but I can not get the wmic.py... I only have one server left that was not updated, so I can test and get this working.  Please let me know if you need anything more?  

[root@netutil ~]# wmic.py -U '******\*******' --namespace 'root/cimv2' '//10.0.0.1' 'SELECT Version FROM Win32_OperatingSystem'
ERROR:root:rpc_s_access_denied
[root@netutil ~]#

**Comment by slyguy2000** [comment]
ha!!! I figured out my problem...   -U "domain\username"%"password" does NOT work!  
but if I use  -U "username"%"password" it works!  

we have 3 NT domains and I needed to distinguish between the servers in each domain.  now I removed the domain from the username and it works!!!  THANK YOU!!!!

**Comment by slyguy2000** [comment]
okay, all my domain machines are working, but local machines are triggering:
UNKNOWN - The WMI query had problems. The error text from wmic is: ERROR:root:rpc_s_access_denied

when I run a test from the command line it works:
[user@netutil ~]$ wmic.py -U administrator%password //10.0.0.1 'select * from Win32_ComputerSystem'
CLASS: Win32_ComputerSystem
Caption|Description|InstallDate|Name|Status|CreationClassName|NameFormat|PrimaryOwnerContact|PrimaryOwnerName|Roles|InitialLoadInfo|LastLoadInfo|PowerManagementSupported|PowerManagementCapabilities|PowerState|ResetCapability|AutomaticResetBootOption|AutomaticManagedPagefile|AutomaticResetCapability|BootROMSupported|BootupState|CurrentTimeZone|DNSHostName|Domain|InfraredSupported|Manufacturer|Model|NetworkServerModeEnabled|OEMLogoBitmap|SupportContactDescription|SystemStartupDelay|SystemStartupOptions|SystemStartupSetting|SystemType|UserName|DomainRole|WakeUpType|OEMStringArray|BootOptionOnLimit|BootOptionOnWatchDog|ResetCount|ResetLimit|PauseAfterReset|PowerOnPasswordStatus|KeyboardPasswordStatus|AdminPasswordStatus|FrontPanelResetStatus|ChassisBootupState|PowerSupplyState|ThermalState|DaylightInEffect|EnableDaylightSavingsTime|NumberOfProcessors|NumberOfLogicalProcessors|TotalPhysicalMemory|PartOfDomain|PCSystemType|PCSystemTypeEx|Workgroup|SystemSKUNumber|SystemFamily|ChassisSKUNumber|BootStatus|HypervisorPresent
nondomainpc|AT/AT COMPATIBLE|None|nondomainpc|OK|Win32_ComputerSystem|None|None|Windows User|[372, 388, 399, 403]|None|None|True|None|0|1|True|True|True|True|Normal boot|-360|nondomainpc|WORKGROUP|False|VMware, Inc.|VMware7,1|True|None|None|None|None|None|x64-based PC|nondomainpc\Administrator|2|6|['[MS_VM_CERT/SHA1/27d66596a61c48dd3dc7216fd715126e33f59ae7]', 'Welcome to the Virtual Machine']|3|3|-1|-1|3932100000|0|3|1|3|3|3|3|True|True|2|4|17178845184|False|1|1|WORKGROUP|None|None|None|[0, 0, 0, 33, 31, 158, 0, 3, 2, 2]|True
[user@netutil ~]$

**Comment by slyguy2000** [comment]
@selcats sorry didn't mean to hijack your thread...

**Comment by rmond38** [comment]
Hi,
I followed all the steps but got an error that I'm not able to resolve:
Here is my wmic.py command:
./wmic.py -U 'domain/user'%'password' --namespace 'root/cimv2' '//10.X.X.XX' 'SELECT Version FROM Win32_OperatingSystem'

And here are the results:
 File "./wmic.py", line 50, in <module>
    elif args.user is not None:
AttributeError: 'Namespace' object has no attribute 'user'

I've tried with many combination (domain, no domain, wildcard, etc...) and still got the same error.
Thanks for your help

**Comment by maldex** [comment]
Hi rmond38
that was my hasty implementation for the -A switch. please see the current pull request

**Comment by rmond38** [comment]
Thanks maldex, you make my day !
It's working fine now with the changes

**Comment by wornet-aer** [comment]
Pull request #8 has been merged now. If anyone still has problems getting it running, please open a seperate issue.
