### ISSUE TITLE
Drop-in replacement not recognised by check_wmi_plus

### ISSUE THREAD

**Issue by garbagexbag** [simply42/check_wmi_plus_wmic_dropin#9]
Hello, has anyone else encountered this issue? Im on debian buster, followed the steps correctly by downloading the .py file, made backup of the old one, moved the .py file to /usr/bin and made a link as ln -s /usr/bin/wmic.py /usr/bin/wmic. 
I confirmed that the link exists but on nagios the check_wmi_plus config keeps yelling:
This plugin requires the linux implementation of wmic eg from zenoss.
Once wmic is installed, configure its location by setting the $wmic_command variable in '/etc/check_wmi_plus/check_wmi_plus.conf'
I verified that the $wmic_command points to /usr/bin/wmic, even changing it directly to /usr/bin/wmic.py gives the same error. Any ideas?

**Comment by wornet-aer** [comment]
Have you verified that the python executable has the correct `chmod` rights and the correct `chown` set?
What happens, if you try to execute it as the user `nagios` or the user your monitoring system is running as?

**Comment by garbagexbag** [comment]
Yes, sorry, seems like it was a rights issue, working when I set chmod 755
